[project]
name = "backloganalyzer"
version = "0.0.1"
description = "Answer questions about your GitHub backlog"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
   "joblib",
   "openai",
   "PyGitHub",
   "numpy"
]
